# Generated by Django 5.1.4 on 2024-12-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=255)),
                ('prenume', models.CharField(max_length=255)),
                ('cnp', models.CharField(max_length=255)),
                ('data_nasterii', models.DateField()),
                ('data_inregistrarii', models.DateField()),
                ('puncte_acumulate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titlu', models.CharField(max_length=255)),
                ('an_aparitie', models.IntegerField()),
                ('pret_bilet', models.FloatField()),
                ('in_program', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rezervare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_film', models.IntegerField()),
                ('id_card_client', models.IntegerField()),
                ('data', models.DateField()),
            ],
        ),
    ]
