# Generated by Django 5.1.4 on 2025-01-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=255)),
                ('prenume', models.CharField(max_length=255)),
                ('parola', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='CardClient',
        ),
        migrations.RenameField(
            model_name='rezervare',
            old_name='id_card_client',
            new_name='id_utilizator',
        ),
    ]
