# Generated by Django 5.1.4 on 2025-01-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_utilizator_delete_cardclient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilizator',
            old_name='prenume',
            new_name='username',
        ),
    ]
